# Besuchen sie editor.swagger.io und pasten Sie den inhalt dieser datei rein, um die Dokumentation graphisch zu sehen.
openapi: "3.0.0"
info:
  version: 1.0.0
  title: Linter REST api

paths:
  /projects:
    get:
      summary: list all inner-source projects
      operationId: AllProjects
      responses:
        '200':
          description: array of Projects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Project'

  /project/{id}:
    get:
      summary: get details for one repo (incl. results)
      operationId: GetProject
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: the project detail and lint results
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Project"
        '404':
          description: Not Found

components:
  parameters:
    id:
      name: id
      in: path
      required: true
      schema:
        type: integer
      description: ProjectID

  schemas:
    Project:
      type: object
      properties:
        id:
          type: integer
        url:
          type: string
          format: uri
        name:
          type: string
        last_lint:
          type: string
          format: date-time
        results:
          type: array
          items:
            $ref: "#/components/schemas/Result"
    
    Result:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        result:
          type: boolean

