name: Build, Test and Package Frontend as Docker Image

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2

    - name: Install packages
      working-directory: ./angular-frontend
      run: npm install # TODO cache them

    - name: Build the FrontEnd
      working-directory: ./angular-frontend
      run: ng build --prod

    - name: Build Docker Image
      run: echo TODO

    - name: Push Docker Image
      run: echo TODO
