name: FrontEnd

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Use Cache
        uses: actions/cache@v2
        with: # caches all npm packages. Updates when frontend/package-lock.json changes
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: sets up npm / node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: install angular CLI
        run: npm install -g @angular/cli
      
      - name: Install packages
        working-directory: ./frontend
        run: npm install

      - name: Build the FrontEnd
        working-directory: ./frontend
        run: ng build --prod
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./frontend  # where the dockerfile is located
          push: true
          tags: amoslinter/frontend:staging
